"""initial migrations

Revision ID: dcf9f0cf78e0
Revises: 
Create Date: 2022-09-05 18:03:41.671035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf9f0cf78e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('condition', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.drop_column('condition')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
